#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7
  - 3.5

services: postgresql

env:

before_install:
  - export DJANGO_SETTINGS_MODULE=OpenGMS.settings
  - export PYTHONPATH=$HOME/builds/shikkanobish/OpenGMS
  - export DEBUG=True
  - export WEB_CONCURRENCY=2
  - export SECRET_KEY="9(-8jpot70a0b=g3gvo1+!c!ujm!5(&a2c+pe+6w6@!f399^h9"
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py migrate