#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.6
  - 2.7

services: postgresql

env:
  - DJANGO=1.4.1
  - WEB_CONCURRENCY=2

before_install:
  - export DJANGO_SETTINGS_MODULE=OpenGMS.settings
  - export PYTHONPATH=$HOME/builds/shikkanobish/OpenGMS
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py syncdb --noinput