# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.FileField(upload_to='media/'),
        ),
    ]
