# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180113_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
