# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180113_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50, null=True)),
                ('order_type', models.CharField(max_length=20)),
                ('design', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('deadline', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('budget', models.IntegerField(default=0)),
                ('shipping_address', models.CharField(max_length=300, null=True)),
                ('specification', models.CharField(max_length=300, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_history', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_username_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_histories',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
