# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180113_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
