# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_pictures'),
        ),
    ]
