# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171015_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
