# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_pictures'),
        ),
    ]
