# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 19, 3, 8, 43, 630771, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
