# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20171121_0944'),
        ('Notifications', '0002_auto_20171219_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.Order'),
        ),
    ]
